# -*- coding: utf-8 -*-
"""Regularized Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pF897VAJ7plW7LjA1ot5paEuI7i4xoSi
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/boston.csv')
df.head()

"""- `crim`  : Tingkat kejahatan per kapita di suatu wilayah.
- `zn`    : Persentase lahan hunian dengan ukuran besar (>25.000 kaki persegi).
- `indus` : Persentase area industri/non-ritel di suatu wilayah.
- `chas`  : Variabel dummy
- `nox`   : Tingkat polusi udara.
- `rm`    : Rata-rata jumlah kamar per rumah.
- `age`   : Persentase rumah tua.
- `dis`   : Jarak ke pusat pekerjaan.
- `rad`   : Indeks akses ke jalan raya utama.
- `tax`   : Besarnya pajak properti.
- `black` : Variabel historis yang merefleksikan komposisi demografis
- `istat` : Persentase penduduk berstatus sosial ekonomi rendah.
- `medv`  : Harga median rumah dalam ribuan dolar (target)

This data relevant for study case house prediction.There are a lot of factor that will make target column influenced by dependence column.All of Dependence variable also familiar with case in real life when we want to buy house.We will found the same with english term or phrase
"""

df.info()

"""#Split Data"""

from sklearn.model_selection import train_test_split

X = df.drop(columns='medv')
y = df['medv']

#split data
X_train, X_test, y_train, y_terst = train_test_split(X,
                                                     y,
                                                     test_size=0.2,
                                                     random_state=42)

print(X_train.shape)
print(X_test.shape)

X_train.info()

X_train.head()

X_train.info()

numeric = ['crim', 'rm', 'tax', 'lstat', 'nox', 'dis']

for col in numeric:
  print(col)
  sns.boxplot(x=X_train[col])
  print('-' * 100)
  plt.show()

for col in numeric:
    q1 = X_train[col].quantile(0.25)
    q3 = X_train[col].quantile(0.75)
    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    # capping outlier
    X_train.loc[X_train[col] < lower, col] = lower
    X_train.loc[X_train[col] > upper, col] = upper

    print(f'{col} after outlier capping')
    sns.boxplot(x=X_train[col])
    plt.show()

#feature selection
X_train_no_chas = X_train.drop('chas', axis=1)
X_test_no_chas = X_test.drop('chas', axis=1)

temp = X_train_no_chas.copy()
temp['medv'] = y_train

corr = temp.corr()['medv'].abs()
print('Every value Featrure that correlation with target column')
print('-' * 100)
print(corr)

selected = corr[corr > 0.3].drop('medv')
print('Feature after filtering with value larger than 30%')
print('-' * 100)
print(selected)

X_train_no_chas = X_train_no_chas[selected.index]
X_test_no_chas = X_test_no_chas[selected.index]

#Multicolinearity Check
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif
from statsmodels.tools.tools import add_constant

X = add_constant(X_train_no_chas)

#List comprehension
vif_df = pd.DataFrame(
    [vif(X.values, i) for i in range(X.shape[1])],
    index=X.columns
).reset_index()

vif_df.columns = ['X', 'vif_score']
vif_df = vif_df.loc[vif_df.X != 'const']
vif_df

df_heatmap = pd.concat(
    [X_train_no_chas, y_train],
    axis=1
)

sns.heatmap(df_heatmap.corr(), annot=True)
plt.show()

"""Feature with high multicolinearity:
- crim & rad
- tax & rad
- tax & crim
"""

X_train_no_chas = X_train_no_chas.drop(['rad', 'tax'], axis=1)
X_test_no_chas = X_test_no_chas.drop(['rad', 'tax'], axis=1)

print(X_train_no_chas)

from statsmodels.stats.outliers_influence import variance_inflation_factor as vif
from statsmodels.tools.tools import add_constant

X = add_constant(X_train_no_chas)

#List comprehension
vif_df = pd.DataFrame(
    [vif(X.values, i) for i in range(X.shape[1])],
    index=X.columns
).reset_index()

vif_df.columns = ['X', 'vif_score']
vif_df = vif_df.loc[vif_df.X != 'const']
vif_df

"""# Model Training (Base Model)

## Ridge
"""

from sklearn.linear_model import Ridge

X_df_train = X_train_no_chas.to_numpy()
y_df_train = y_train.to_numpy()
y_df_train = y_df_train.reshape(len(y_df_train))

ridge_reg = Ridge()
ridge_reg.fit(X_df_train, y_df_train) #training

X_train_no_chas.columns.tolist()

data = X_train_no_chas
model_ridge = ridge_reg

#mencari koefisien regresi
coef_df = pd.DataFrame(
    {'feature' : ['intercept'] + data.columns.tolist(),
     'coef' : [model_ridge.intercept_] + model_ridge.coef_.tolist()}
)
coef_df

"""## Lasso"""

from sklearn.linear_model import Lasso

lasso_reg = Lasso()
lasso_reg.fit(X_df_train, y_df_train)

data = X_train_no_chas   # DataFrame, bukan NumPy
model = lasso_reg

coef_df = pd.DataFrame({
    'feature': ['intercept'] + data.columns.tolist(),
    'coefficient': [model.intercept_] + model.coef_.tolist()
})

coef_df

"""#Find the Best Lambda

"""

from sklearn.model_selection import train_test_split

feature = df.drop('medv', axis=1)
target = df['medv']

df = df.dropna()
X = df.drop('medv')
y = df['medv']

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.4, random_state=42
)

X_df_train = X_train_no_chas.to_numpy()
y_df_train = y_train.to_numpy()
y_df_train = y_df_train.reshape(len(y_df_train))

from sklearn.linear_model import Ridge

ridge_reg_pointzeroone = Ridge(alpha=0.01, random_state=42)
ridge_reg_pointone = Ridge(alpha=0.1, random_state=42)
ridge_reg_one = Ridge(alpha=1, random_state=42)
ridge_reg_ten = Ridge(alpha=10, random_state=42)

ridge_reg_pointzeroone.fit(X_df_train, y_df_train)
ridge_reg_pointone.fit(X_df_train, y_df_train)
ridge_reg_one.fit(X_df_train, y_df_train)
ridge_reg_ten.fit(X_df_train, y_df_train)

from sklearn.metrics import mean_squared_error

X_df_validation = feature_validation.to_numpy()
y_df_validation = target_validation.to_numpy()
y_admit_validation = y_df_validation.reshape(len(y_df_validation))

alphas = [0.01, 0.1, 1, 10]
models = [ridge_reg_pointzeroone, ridge_reg_pointone, ridge_reg_one, ridge_reg_ten]

zip(models, alphas)

for model, alpha in zip(models, alphas):
    print(model, alpha)

target.describe()

for model, alpha in zip(models, alphas):
    y_pred = model.predict(X_df_validation)
    mse = mean_squared_error(y_df_validation, y_pred)
    print(f'Mean Squared Error for alpha = {alpha}: mse: {mse}')
    rmse = np.sqrt(mse)
    print(f'Root Mean Squared Error for alpha = {alpha}: rmse: {rmse}')
    print()